tag: 5.4.3

controller:
  replicas: 3
  env: 
  - name: NV_PLATFORM_INFO
    value: "platform=Kubernetes:GKE"
  internal:
    certificate:
      secret: "neuvector-internal-certs"
  secret:
    enabled: true
    data:
      userinitcfg.yaml: 
        always_reload: true
        users:
        -
          Fullname: admin
          Password: 
          Role: admin

manager:
  svc:
    type: LoadBalancer

cve:
  scanner:
    replicas: 2
  internal:
    certificate:
      secret: "neuvector-internal-certs"

enforcer:
  internal:
    certificate:
      secret: "neuvector-internal-certs"

resources:
  limits:
    cpu: 400m
    memory: 2792Mi
  requests:
    cpu: 100m
    memory: 2280Mi

containerd:
  enabled: true
  path: /var/run/containerd/containerd.sock
